name: books_and_details
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  cloud_firestore: ^4.5.1
  convex_bottom_bar: ^3.2.0
  dynamic_color: ^1.6.3
  firebase_auth: ^4.4.1
  firebase_core: ^2.9.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.5
  get: ^4.6.5
  google_sign_in: ^6.1.0
  provider: ^6.0.5
  shared_preferences: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/